Table Grades {
  grade_id int [pk]
  student_id int
  subject_id int
  class_id int
  assessment_type int
  score decimal(5,2)
  max_score decimal(5,2)
  recorded_by int
  date_recorded date
  notes text
}

Table Assessments {
  assessment_id int [pk]
  name varchar
  weight decimal(5,2)
}
